config/routes.rb
Rails.application.routes.draw do

  get 'terms_and_provider/term'=> 'terms_and_provider#term'
  get 'terms_and_provider/privacy'
  get 'terms_and_provider/provider'
  get 'item/order'
  get 'item/history'
  get 'item/transactions'
  get 'admin/history'
  get 'admin/index'
  get 'admin/funds'
  get 'admin/item'
  get "add_order" => redirect { |params, request| "item/add_order?#{request.params.to_query}" }
  # devise_for :users , controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  devise_for :users
  
  match ':controller(/:action(/:id))', :via => [:get, :post, :patch]
  match ':controller(/:action)', :via => [:get, :post, :patch]
  root "item#order"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aldaim Lunch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= javascript_include_tag 'application'  %>
    <%= javascript_include_tag Sync.adapter_javascript_url %>

    <style type="text/css">
      .dropdown-toggle:active, .open .dropdown-toggle {background:#333 !important; color:#FFF !important;}
    </style>


    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="http://cdn.jsdelivr.net/fontawesome/4.3.0/css/font-awesome.min.css">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.0/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.0/js/bootstrap-select.min.js"></script>

  </head>

  <body style="padding-top: 70px;">

    <nav class="navbar navbar-default navbar-fixed-top" style="background:#333;">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if user_signed_in? && current_user.role == nil%>
            <%= link_to(image_tag('logo.png', size: '100x150',:class => "navbar-brand"),  item_order_path  ) %>
          <% elsif  user_signed_in? && current_user.role == "admin"%>
            <%= link_to(image_tag('logo.png', size: '100x150',:class => "navbar-brand"),  admin_index_path  ) %>
          <% else%>
            <%= link_to(image_tag('logo.png', size: '100x150',:class => "navbar-brand")  ) %>
          <% end %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="" >
                <% if current_user.balance == nil && current_user.role == nil %>
                  <a href="#" style="color:white;">Balance <span class="badge" style="background:#00A59B;" >0 </a>
                <%elsif current_user.role == nil%> 
                  <a href="#" style="color:white;">Balance <span class="badge" style="background:#00A59B;" ><%=current_user.balance%> </a>
                <% end %>
              </span></li>
              
              <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="color:white;">
                  <%if current_user.avatar_file_name == nil%>
                    <%= image_tag('avatar.png', size: '24x24') %>                   
                  <% else %>
                    <%= image_tag(current_user.avatar.url(:thumb), size: '24x24') %>                   
                  <% end %>
                  <span class="caret"></span>
                </a>

                <ul class="dropdown-menu">
                  <li><a href="#">Signed in as: <br/> <small style="color:grey;"><%=  current_user.email %></small></a></li>
                  <li><%= link_to('Edit profile', edit_user_registration_path)%></li>
                  <% if current_user.role == nil %>
                  <li><%= link_to('History', item_history_path)%></li>
                  <li><%= link_to('Transactions', item_transactions_path)%></li>
                  <% end %>
                  <% if current_user.role == 'admin' %>
                  <li><%= link_to('History', admin_history_path)%></li>
                  <li><%= link_to('Funds', admin_funds_path)%></li>
                  <li><%= link_to('Items', admin_item_path)%></li>
                  <% end %>
                  <li><%= link_to('Logout', destroy_user_session_path, :method => "delete", id: 'logout')%></li>
               </ul>
             </li>
              
            <% else %>
              <li><%= link_to('Signup', new_user_registration_path, :style => 'color:white')%></li>
              <li><%= link_to('Signin', new_user_session_path, :style => 'color:white')%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="row">
          <div class="col-md-offset-3 col-md-6 text-center">
            <marquee behavior="scroll" direction="left">Yay! Now aldaimers can order lunch online.</marquee>
          </div>
        </div>
  	<div>

    <div class="row text-center">
      <% if !flash[:notice].blank? %>
        <span class="label label-success"><%= flash[:notice]%></span>
      <% end %>

      <% if !flash[:alert].blank? %>
        <span class="label label-danger"><%= flash[:alert]%></span>
      <% end %>
    </div>

    <%= yield %>


    <div class="col-lg-12 footer navbar-fixed-bottom">
      <div class="col-md-12">
        <% if user_signed_in? && current_user.role == nil %>
          <p class="muted pull-right">© Copyrights 2016 - Aldaim Lunch By Mohammad Numan Waheed.</p>
        <% elsif !user_signed_in? %>
          <p class="muted pull-right">© Copyrights 2016 - Aldaim Lunch By Mohammad Numan Waheed.</p>
        <% end %>
      </div>
    </div>

  </body>
</html>